name: Build with NDK and Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build with NDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Run ndk-build
        working-directory: ./jni
        run: ndk-build

      - name: Archive build output
        run: |
          mkdir -p output
          cp -r ./libs output/libs

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/libs/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}